--- 
backend: vmware
buildtype: clone
application: testapp
cpus: 1
disks: 
  - 
    name: disk0
    datastore: any
    size: 10
  -
    name: disk1
    datastore: any
    size: 10
guestid: ubuntu64Guest
mem: 1024
name: testvm57cloudinit
networks: 
  - 
    name: VM Network
    vlan: 1
  -
    name: VM Network
    vlan: 2
user: pgaw
vm_version: vmx-10
vm_folder: 'test'
datastore: zpool0-vms
datacenter: lab
cluster: cluster
resourcepool: Resources
iso: '[zpool0-vms] isos/chroot.iso'
template: bakery-win2016-base-2021-08-23-21-39-release
cloudinit_metadata: |
  instance-id: cloud-vm
  local-hostname: cloud-vm
  admin-username: cloud-username
  admin-password: Passw0rd!
cloudinit_userdata: |
  Content-Type: multipart/mixed; boundary="===123456789"
  MIME-Version: 1.0

  --===123456789
  Content-Type: text/cloud-config; charset="us-ascii"
  MIME-Version: 1.0
    Content-Transfer-Encoding: 7bit
    Content-Disposition: attachment; filename="cloud-config"

    set_timezone: US/Pacific
    set_hostname: philtest123

  --===123456789
  Content-Type: text/x-shellscript; charset="us-ascii"
  MIME-Version: 1.0
    Content-Transfer-Encoding: 7bit
    Content-Disposition: attachment; filename="doPsStuff.ps1"

  #ps1_sysnative
  New-NetIpAddress -InterfaceAlias Ethernet0 -IPAddress 192.168.100.1 -PrefixLength 24 -DefaultGateway 192.168.100.2
  Set-DnsClientServerAddress -InterfaceAlias Ethernet0 -ServerAddresses("8.8.8.8")
  Set-DnsClient -InterfaceAlias Ethernet0 -ConnectionSpecificSuffix "tuxgrid.com"
  Set-DnsClientGlobalSetting -SuffixSearchList @("tuxgrid.com")
  Get-Disk | Where-Object PartitionStyle -Eq "RAW" | Initialize-Disk -PassThru | New-Partition -AssignDriveLetter -UseMaximumSize | Format-Volume
  Disable-NetAdapterBinding -InterfaceAlias "Ethernet0" -ComponentID ms_tcpip6
  Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
  Set-Service -Name TermService -StartType Automatic -Status Running
  Set-Service -Name UmRdpService -Status Running
  Set-Service -Name SessionEnv -Status Running
  Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
  $password = ConvertTo-SecureString Password01 -AsPlainText -Force
  $newUser = New-LocalUser -Name "Phil" -Password $password -FullName "Phil Test" -Description "Phil Test"
  Add-LocalGroupMember -Group "Administrators" -Member "Phil Test"

