--- 
backend: vmware
buildtype: clone
application: testapp
cpus: 1
disks: 
  - 
    name: disk0
    datastore: any
    size: 10
  -
    name: disk1
    datastore: any
    size: 10
guestid: ubuntu64Guest
mem: 2048
networks: 
  - 
    name: VM Network
    vlan: 1
  -
    name: VM Network
    vlan: 2
user: pgaw
vm_version: vmx-10
vm_folder: 'test'
datastore: zpool0-vms
datacenter: lab
cluster: cluster
resourcepool: Resources
iso: '[zpool0-vms] isos/chroot.iso'
template: bakery-win2016-base-2021-08-25-09-24-release
name: test1234
network:
  ip: "198.244.132.187"
  prefix: "28"
  gateway: "198.244.132.177"
  dns: 8.8.8.8
  domain: tuxgrid.com
metadata:
  admin_username: "Admin"
  admin_password: "Temp123!"
  host: "test1234"
  fqdn: "test1234.tuxgrid.com"
  timezone: Europe/London
salt:
  minion_name: "test1234"
  master_name: "saltmaster.tuxgrid.com"
